<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260422195027 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE licence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero VARCHAR(50) NOT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, joueur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1DAAE648A9E2D76C ON licence (joueur_id)');
        $this->addSql('ALTER TABLE licence ADD CONSTRAINT FK_1DAAE648A9E2D76C FOREIGN KEY (joueur_id) REFERENCES joueur (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE licence DROP CONSTRAINT FK_1DAAE648A9E2D76C');
        $this->addSql('DROP TABLE licence');
    }
}
