<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260422204321 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE blessure (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_fin_estimee TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, joueur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_56D071A2A9E2D76C ON blessure (joueur_id)');
        $this->addSql('CREATE TABLE rencontre (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, adversaire VARCHAR(255) NOT NULL, date_match TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE rencontre_joueur (rencontre_id INT NOT NULL, joueur_id INT NOT NULL, PRIMARY KEY (rencontre_id, joueur_id))');
        $this->addSql('CREATE INDEX IDX_490DF56F6CFC0818 ON rencontre_joueur (rencontre_id)');
        $this->addSql('CREATE INDEX IDX_490DF56FA9E2D76C ON rencontre_joueur (joueur_id)');
        $this->addSql('CREATE TABLE statistique (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, minutes_jouees INT NOT NULL, buts INT NOT NULL, passes INT NOT NULL, distance_km DOUBLE PRECISION DEFAULT NULL, joueur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_73A038ADA9E2D76C ON statistique (joueur_id)');
        $this->addSql('ALTER TABLE blessure ADD CONSTRAINT FK_56D071A2A9E2D76C FOREIGN KEY (joueur_id) REFERENCES joueur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rencontre_joueur ADD CONSTRAINT FK_490DF56F6CFC0818 FOREIGN KEY (rencontre_id) REFERENCES rencontre (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rencontre_joueur ADD CONSTRAINT FK_490DF56FA9E2D76C FOREIGN KEY (joueur_id) REFERENCES joueur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE statistique ADD CONSTRAINT FK_73A038ADA9E2D76C FOREIGN KEY (joueur_id) REFERENCES joueur (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE blessure DROP CONSTRAINT FK_56D071A2A9E2D76C');
        $this->addSql('ALTER TABLE rencontre_joueur DROP CONSTRAINT FK_490DF56F6CFC0818');
        $this->addSql('ALTER TABLE rencontre_joueur DROP CONSTRAINT FK_490DF56FA9E2D76C');
        $this->addSql('ALTER TABLE statistique DROP CONSTRAINT FK_73A038ADA9E2D76C');
        $this->addSql('DROP TABLE blessure');
        $this->addSql('DROP TABLE rencontre');
        $this->addSql('DROP TABLE rencontre_joueur');
        $this->addSql('DROP TABLE statistique');
    }
}
